const IMAGES = {
    BackgroundImage : new URL('./bg.jpg', import.meta.url).href,
    BackgroundImagee2 : new URL('./bg.png', import.meta.url).href,
    Logo: new URL('./logo.svg', import.meta.url).href,
    Menu: new URL('./menu.png', import.meta.url).href,
    BackgroundImage2: new URL('./bg2.png', import.meta.url).href,
    Exercise1: new URL('./exercise1.svg', import.meta.url).href,
    Exercise2: new URL('./exercise2.svg', import.meta.url).href,
    MaskGroup1: new URL('./maskgroup1.svg', import.meta.url).href,
    MaskGroup2: new URL('./maskgroup2.svg', import.meta.url).href,
    MaskGroup3: new URL('./maskgroup3.svg', import.meta.url).href,
    Google: new URL('./google.svg', import.meta.url).href,
    App: new URL('./app.svg', import.meta.url).href,
    Mobile: new URL('./mobile.svg', import.meta.url).href,
    Ruster: new URL('./ruster.svg', import.meta.url).href,
    Velites: new URL('./velites.svg', import.meta.url).href,
    Company1: new URL('./a.svg', import.meta.url).href,
    Company2: new URL('./b.svg', import.meta.url).href,
    Company3: new URL('./c.svg', import.meta.url).href,
    Company4: new URL('./d.svg', import.meta.url).href,
    Company5: new URL('./e.svg', import.meta.url).href,
    Company6: new URL('./f.svg', import.meta.url).href,
    Company7: new URL('./g.svg', import.meta.url).href,
    Tiktok: new URL('./tiktok.svg', import.meta.url).href,
    Insta: new URL('./insta.svg', import.meta.url).href,
    Youtube: new URL('./youtube.svg', import.meta.url).href,
    Facebook: new URL('./fb.svg', import.meta.url).href,
    Paypal: new URL('./paypal.svg', import.meta.url).href,
    ApplePay: new URL('./applepay.svg', import.meta.url).href,
    Visa: new URL('./visa.svg', import.meta.url).href,
    AndroidPay: new URL('./androidpay.svg', import.meta.url).href,
    User: new URL('./user.svg', import.meta.url).href,
    DownArrow: new URL('./downarrow.svg', import.meta.url).href,
    Workout: new URL('./workout.png', import.meta.url).href,
    MenuDown: new URL('./menudown.svg', import.meta.url).href,
    MenuRight: new URL('./menuright.svg', import.meta.url).href,
    Description: new URL('./dashboard.png', import.meta.url).href,
    Leaderboard: new URL('./leaderboard.svg', import.meta.url).href,
    Preferences: new URL('./preferences.svg', import.meta.url).href,
    Retry: new URL('./retry.svg', import.meta.url).href,
    Running: new URL('./running.svg', import.meta.url).href,
    Profile: new URL('./man.svg', import.meta.url).href,
    Ayuda: new URL('./ayuda.svg', import.meta.url).href,
    RightSession: new URL('./rightsession.svg', import.meta.url).href,
    DashboardImage: new URL('./dashboardimg.jpg', import.meta.url).href,
    Edit: new URL('./pencil.svg', import.meta.url).href,
    InputImage: new URL('./inputimage.svg', import.meta.url).href,
    Deadlift: new URL('./deadlift.svg', import.meta.url).href,
    Crossfit: new URL('./crossfit.jpg', import.meta.url).href,
    Athlete: new URL('./athlete.png', import.meta.url).href,
    Search: new URL('./search.svg', import.meta.url).href,
    Lines: new URL('./lines.svg', import.meta.url).href,
    calendar: new URL('./calendar.png', import.meta.url).href,
    timetable: new URL('./timetable.png', import.meta.url).href,
    wod: new URL('./wod.webp', import.meta.url).href,
    
}

export default IMAGES;